import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1789138279976 implements MigrationInterface {
    name = 'Migration1789138279976'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("uid" character varying NOT NULL, "name" character varying NOT NULL, "docNumberPerson" bigint, "docNumberBusiness" bigint, "gender" "public"."users_gender_enum" NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "isActivated" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_6e20ce1edf0678a09f1963f9587" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "platforms" ("uid" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "category" "public"."platforms_category_enum" NOT NULL, "isActivated" boolean NOT NULL DEFAULT true, "createdBy" character varying(255), "updatedBy" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5bf1e9dbac57a0ee34037a63287" UNIQUE ("slug"), CONSTRAINT "PK_a880fcef162917555200aa684e5" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "memberships" ("uid" character varying(50) NOT NULL, "userUID" character varying(50) NOT NULL, "platformUID" character varying(50) NOT NULL, "role" "public"."memberships_role_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b15f4863b44854b6e9123508982" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_membership_user_platform" ON "memberships" ("userUID", "platformUID") `);
        await queryRunner.query(`CREATE TABLE "transaction_categories" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40), "name" character varying(100) NOT NULL, "type" "public"."transaction_categories_type_enum" NOT NULL, "color" character varying(20), "description" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_35470bcdf2dc99f03ca237224ce" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "transactions" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40) NOT NULL, "categoryUID" character varying(40) NOT NULL, "type" "public"."transactions_type_enum" NOT NULL, "description" character varying(255) NOT NULL, "source" "public"."transactions_source_enum", "sourceUID" character varying(40), "amount" numeric(14,2) NOT NULL, "occurredAt" TIMESTAMP NOT NULL, "notes" text, "createdBy" character varying(40) NOT NULL, "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c3dcba0b0a4c2ed3442124475bf" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "losses" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40), "transactionUID" character varying(40), "productUID" character varying(40), "quantity" numeric(10,2) NOT NULL, "unitCost" numeric(12,2) NOT NULL, "totalCost" numeric(14,2) NOT NULL, "reason" "public"."losses_reason_enum" NOT NULL, "description" text, "occurredAt" TIMESTAMP NOT NULL, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ad6c828f08669f3bf8cb2f27f96" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "nutritious" ("uid" character varying(40) NOT NULL, "name" character varying(100) NOT NULL, "startWeek" integer NOT NULL, "endWeek" integer NOT NULL, "minimumCrudeProtein" numeric(5,2) NOT NULL, "maximumCrudeProtein" numeric(5,2) NOT NULL, "metabolizableEnergy" numeric(10,2), "crudeFiber" numeric(5,2), "calcium" numeric(5,2), "phosphorus" numeric(5,2), "sodium" numeric(5,2), "lysine" numeric(5,2), "methionine" numeric(5,2), "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_03cea6d953790084684791b2dc4" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40) NOT NULL, "name" character varying(100) NOT NULL, "category" "public"."inventory_items_category_enum" NOT NULL, "trackStock" boolean NOT NULL, "unit" "public"."inventory_items_unit_enum" NOT NULL, "crudeProtein" numeric(5,2), "metabolizableEnergy" numeric(10,2), "crudeFiber" numeric(5,2), "calcium" numeric(5,2), "minimumStock" numeric(10,2), "description" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_58194d6a71b9d1c2fd1c8cb5166" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "weights" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40), "flockUID" character varying(40) NOT NULL, "weighingDate" date NOT NULL, "averageWeight" numeric(10,2) NOT NULL, "sampleSize" integer, "notes" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e6de09cb6a52cbc17927e45672" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "vaccinations" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40), "flockUID" character varying(40) NOT NULL, "itemUID" character varying(40) NOT NULL, "applicationDate" date NOT NULL, "dose" character varying(100), "batch" character varying(100), "nextDoseDate" date, "notes" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1cf6ee918c56944a28eebfce3f2" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "mortalities" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40), "flockUID" character varying(40) NOT NULL, "mortalityDate" date NOT NULL, "quantity" integer NOT NULL, "cause" character varying(50), "notes" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4924fec1ed2ba62be6f95f40ce" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "flocks" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40), "name" character varying(255) NOT NULL, "quantity" integer NOT NULL, "status" character varying(50) NOT NULL, "birthDate" date, "arrivalDate" date, "description" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_024d75ea3d461a4b113ee46ba38" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "egg_productions" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40), "flockUID" character varying(40) NOT NULL, "productionDate" date NOT NULL, "totalEggs" integer NOT NULL, "crackedEggs" integer, "dirtyEggs" integer, "discardedEggs" integer, "notes" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de4584d3e846f18d83998315e8a" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "breeds" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40), "name" character varying(255) NOT NULL, "scientificName" character varying(255), "eggColor" character varying(50), "breedPurpose" character varying(50), "description" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c2d5cef00e335e60d448e4e6fc" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "feeds" ("uid" character varying(40) NOT NULL, "platformUID" character varying(40) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "createdBy" character varying(40), "updatedBy" character varying(40), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_34f96d18377dcb000ceedf7248d" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "feed_items" ("uid" character varying(40) NOT NULL, "feedUID" character varying(40) NOT NULL, "inventoryItemUID" character varying(40) NOT NULL, "inclusionPercentage" numeric(5,2) NOT NULL, CONSTRAINT "PK_b8aeea6459e2e9f203be6645a02" PRIMARY KEY ("uid"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "feed_items"`);
        await queryRunner.query(`DROP TABLE "feeds"`);
        await queryRunner.query(`DROP TABLE "breeds"`);
        await queryRunner.query(`DROP TABLE "egg_productions"`);
        await queryRunner.query(`DROP TABLE "flocks"`);
        await queryRunner.query(`DROP TABLE "mortalities"`);
        await queryRunner.query(`DROP TABLE "vaccinations"`);
        await queryRunner.query(`DROP TABLE "weights"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TABLE "nutritious"`);
        await queryRunner.query(`DROP TABLE "losses"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TABLE "transaction_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_membership_user_platform"`);
        await queryRunner.query(`DROP TABLE "memberships"`);
        await queryRunner.query(`DROP TABLE "platforms"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
