services:
    postgres:
        image: postgres:17
        container_name: core-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: db_core
            POSTGRES_USER: flat
            POSTGRES_PASSWORD: Q7!mZ@4Kp%9SxL2$
        ports:
            - "5432:5432"
        volumes:
            - core_postgres_data:/var/lib/postgresql/data

volumes:
    core_postgres_data: