import { DataSource } from "typeorm";

import { WeightStandardEntity } from "@/modules/farmora/flock/weight-standard/entities/weight-standard.entity";

export async function seedWeightStandard(dataSource: DataSource): Promise<void> {
    const weightStandardRepository = dataSource.getRepository(WeightStandardEntity);

    const weightStandards = weightStandardRepository.create([
        // ============================================================
        // GLC
        // Peso médio publicado pela Avifran.
        // Faixa estimada: ±10%, conforme orientação zootécnica.
        // ============================================================

        {
            uid: "wst-glc-01",
            breed: "GLC",
            week: 1,
            minWeight: 59,
            targetWeight: 65,
            maxWeight: 72,
        },
        {
            uid: "wst-glc-07",
            breed: "GLC",
            week: 7,
            minWeight: 500,
            targetWeight: 555,
            maxWeight: 611,
        },
        {
            uid: "wst-glc-13",
            breed: "GLC",
            week: 13,
            minWeight: 981,
            targetWeight: 1090,
            maxWeight: 1199,
        },
        {
            uid: "wst-glc-17",
            breed: "GLC",
            week: 17,
            minWeight: 1233,
            targetWeight: 1370,
            maxWeight: 1507,
        },
        {
            uid: "wst-glc-35",
            breed: "GLC",
            week: 35,
            minWeight: 1710,
            targetWeight: 1900,
            maxWeight: 2090,
        },

        // ============================================================
        // BKB
        // Peso médio publicado pela Avifran.
        // Faixa estimada: ±10%, conforme orientação zootécnica.
        // ============================================================

        {
            uid: "wst-bkb-01",
            breed: "BKB",
            week: 1,
            minWeight: 56,
            targetWeight: 62,
            maxWeight: 68,
        },
        {
            uid: "wst-bkb-07",
            breed: "BKB",
            week: 7,
            minWeight: 444,
            targetWeight: 493,
            maxWeight: 542,
        },
        {
            uid: "wst-bkb-13",
            breed: "BKB",
            week: 13,
            minWeight: 871,
            targetWeight: 968,
            maxWeight: 1065,
        },
        {
            uid: "wst-bkb-17",
            breed: "BKB",
            week: 17,
            minWeight: 1120,
            targetWeight: 1244,
            maxWeight: 1368,
        },
        {
            uid: "wst-bkb-35",
            breed: "BKB",
            week: 35,
            minWeight: 1665,
            targetWeight: 1850,
            maxWeight: 2035,
        },

        // ============================================================
        // NOVOgen COLOR BLUE
        // ============================================================

        {
            uid: "wst-novogen-color-blue-01",
            breed: "NOVOgen Color Blue",
            week: 1,
            minWeight: 62,
            targetWeight: 65,
            maxWeight: 68,
        },
        {
            uid: "wst-novogen-color-blue-02",
            breed: "NOVOgen Color Blue",
            week: 2,
            minWeight: 115,
            targetWeight: 120,
            maxWeight: 125,
        },
        {
            uid: "wst-novogen-color-blue-03",
            breed: "NOVOgen Color Blue",
            week: 3,
            minWeight: 190,
            targetWeight: 195,
            maxWeight: 200,
        },
        {
            uid: "wst-novogen-color-blue-04",
            breed: "NOVOgen Color Blue",
            week: 4,
            minWeight: 270,
            targetWeight: 277.5,
            maxWeight: 285,
        },
        {
            uid: "wst-novogen-color-blue-05",
            breed: "NOVOgen Color Blue",
            week: 5,
            minWeight: 365,
            targetWeight: 375,
            maxWeight: 385,
        },
        {
            uid: "wst-novogen-color-blue-06",
            breed: "NOVOgen Color Blue",
            week: 6,
            minWeight: 455,
            targetWeight: 467.5,
            maxWeight: 480,
        },
        {
            uid: "wst-novogen-color-blue-07",
            breed: "NOVOgen Color Blue",
            week: 7,
            minWeight: 545,
            targetWeight: 557.5,
            maxWeight: 570,
        },
        {
            uid: "wst-novogen-color-blue-08",
            breed: "NOVOgen Color Blue",
            week: 8,
            minWeight: 630,
            targetWeight: 645,
            maxWeight: 660,
        },
        {
            uid: "wst-novogen-color-blue-09",
            breed: "NOVOgen Color Blue",
            week: 9,
            minWeight: 710,
            targetWeight: 730,
            maxWeight: 750,
        },
        {
            uid: "wst-novogen-color-blue-10",
            breed: "NOVOgen Color Blue",
            week: 10,
            minWeight: 795,
            targetWeight: 817.5,
            maxWeight: 840,
        },
        {
            uid: "wst-novogen-color-blue-11",
            breed: "NOVOgen Color Blue",
            week: 11,
            minWeight: 880,
            targetWeight: 902.5,
            maxWeight: 925,
        },
        {
            uid: "wst-novogen-color-blue-12",
            breed: "NOVOgen Color Blue",
            week: 12,
            minWeight: 965,
            targetWeight: 990,
            maxWeight: 1015,
        },
        {
            uid: "wst-novogen-color-blue-13",
            breed: "NOVOgen Color Blue",
            week: 13,
            minWeight: 1050,
            targetWeight: 1077.5,
            maxWeight: 1105,
        },
        {
            uid: "wst-novogen-color-blue-14",
            breed: "NOVOgen Color Blue",
            week: 14,
            minWeight: 1135,
            targetWeight: 1162.5,
            maxWeight: 1190,
        },
        {
            uid: "wst-novogen-color-blue-15",
            breed: "NOVOgen Color Blue",
            week: 15,
            minWeight: 1215,
            targetWeight: 1245,
            maxWeight: 1275,
        },
        {
            uid: "wst-novogen-color-blue-16",
            breed: "NOVOgen Color Blue",
            week: 16,
            minWeight: 1295,
            targetWeight: 1327.5,
            maxWeight: 1360,
        },
        {
            uid: "wst-novogen-color-blue-17",
            breed: "NOVOgen Color Blue",
            week: 17,
            minWeight: 1380,
            targetWeight: 1415,
            maxWeight: 1450,
        },
        {
            uid: "wst-novogen-color-blue-18",
            breed: "NOVOgen Color Blue",
            week: 18,
            minWeight: 1455,
            targetWeight: 1490,
            maxWeight: 1525,
        },

        // ============================================================
        // NOVOgen COLOR GREEN
        // ============================================================

        {
            uid: "wst-novogen-color-green-01",
            breed: "NOVOgen Color Green",
            week: 1,
            minWeight: 62,
            targetWeight: 65,
            maxWeight: 68,
        },
        {
            uid: "wst-novogen-color-green-02",
            breed: "NOVOgen Color Green",
            week: 2,
            minWeight: 115,
            targetWeight: 120,
            maxWeight: 125,
        },
        {
            uid: "wst-novogen-color-green-03",
            breed: "NOVOgen Color Green",
            week: 3,
            minWeight: 190,
            targetWeight: 195,
            maxWeight: 200,
        },
        {
            uid: "wst-novogen-color-green-04",
            breed: "NOVOgen Color Green",
            week: 4,
            minWeight: 270,
            targetWeight: 277.5,
            maxWeight: 285,
        },
        {
            uid: "wst-novogen-color-green-05",
            breed: "NOVOgen Color Green",
            week: 5,
            minWeight: 365,
            targetWeight: 375,
            maxWeight: 385,
        },
        {
            uid: "wst-novogen-color-green-06",
            breed: "NOVOgen Color Green",
            week: 6,
            minWeight: 455,
            targetWeight: 467.5,
            maxWeight: 480,
        },
        {
            uid: "wst-novogen-color-green-07",
            breed: "NOVOgen Color Green",
            week: 7,
            minWeight: 545,
            targetWeight: 557.5,
            maxWeight: 570,
        },
        {
            uid: "wst-novogen-color-green-08",
            breed: "NOVOgen Color Green",
            week: 8,
            minWeight: 630,
            targetWeight: 645,
            maxWeight: 660,
        },
        {
            uid: "wst-novogen-color-green-09",
            breed: "NOVOgen Color Green",
            week: 9,
            minWeight: 710,
            targetWeight: 730,
            maxWeight: 750,
        },
        {
            uid: "wst-novogen-color-green-10",
            breed: "NOVOgen Color Green",
            week: 10,
            minWeight: 795,
            targetWeight: 817.5,
            maxWeight: 840,
        },
        {
            uid: "wst-novogen-color-green-11",
            breed: "NOVOgen Color Green",
            week: 11,
            minWeight: 880,
            targetWeight: 902.5,
            maxWeight: 925,
        },
        {
            uid: "wst-novogen-color-green-12",
            breed: "NOVOgen Color Green",
            week: 12,
            minWeight: 965,
            targetWeight: 990,
            maxWeight: 1015,
        },
        {
            uid: "wst-novogen-color-green-13",
            breed: "NOVOgen Color Green",
            week: 13,
            minWeight: 1050,
            targetWeight: 1077.5,
            maxWeight: 1105,
        },
        {
            uid: "wst-novogen-color-green-14",
            breed: "NOVOgen Color Green",
            week: 14,
            minWeight: 1135,
            targetWeight: 1162.5,
            maxWeight: 1190,
        },
        {
            uid: "wst-novogen-color-green-15",
            breed: "NOVOgen Color Green",
            week: 15,
            minWeight: 1215,
            targetWeight: 1245,
            maxWeight: 1275,
        },
        {
            uid: "wst-novogen-color-green-16",
            breed: "NOVOgen Color Green",
            week: 16,
            minWeight: 1295,
            targetWeight: 1327.5,
            maxWeight: 1360,
        },
        {
            uid: "wst-novogen-color-green-17",
            breed: "NOVOgen Color Green",
            week: 17,
            minWeight: 1380,
            targetWeight: 1415,
            maxWeight: 1450,
        },
        {
            uid: "wst-novogen-color-green-18",
            breed: "NOVOgen Color Green",
            week: 18,
            minWeight: 1455,
            targetWeight: 1490,
            maxWeight: 1525,
        },

        // ============================================================
        // ISA BROWN
        // ============================================================

        {
            uid: "wst_isa-brown-01",
            breed: "ISA Brown",
            week: 1,
            minWeight: 64,
            targetWeight: 65.5,
            maxWeight: 67,
        },
        {
            uid: "wst_isa-brown-02",
            breed: "ISA Brown",
            week: 2,
            minWeight: 132,
            targetWeight: 135.5,
            maxWeight: 139,
        },
        {
            uid: "wst_isa-brown-03",
            breed: "ISA Brown",
            week: 3,
            minWeight: 211,
            targetWeight: 216,
            maxWeight: 221,
        },
        {
            uid: "wst_isa-brown-04",
            breed: "ISA Brown",
            week: 4,
            minWeight: 296,
            targetWeight: 304,
            maxWeight: 312,
        },
        {
            uid: "wst_isa-brown-05",
            breed: "ISA Brown",
            week: 5,
            minWeight: 388,
            targetWeight: 398,
            maxWeight: 408,
        },
        {
            uid: "wst_isa-brown-06",
            breed: "ISA Brown",
            week: 6,
            minWeight: 485,
            targetWeight: 497.5,
            maxWeight: 510,
        },
        {
            uid: "wst_isa-brown-07",
            breed: "ISA Brown",
            week: 7,
            minWeight: 584,
            targetWeight: 599,
            maxWeight: 614,
        },
        {
            uid: "wst_isa-brown-08",
            breed: "ISA Brown",
            week: 8,
            minWeight: 685,
            targetWeight: 702.5,
            maxWeight: 720,
        },
        {
            uid: "wst_isa-brown-09",
            breed: "ISA Brown",
            week: 9,
            minWeight: 786,
            targetWeight: 806,
            maxWeight: 826,
        },
        {
            uid: "wst_isa-brown-10",
            breed: "ISA Brown",
            week: 10,
            minWeight: 886,
            targetWeight: 909,
            maxWeight: 932,
        },
        {
            uid: "wst_isa-brown-11",
            breed: "ISA Brown",
            week: 11,
            minWeight: 984,
            targetWeight: 1009,
            maxWeight: 1034,
        },
        {
            uid: "wst_isa-brown-12",
            breed: "ISA Brown",
            week: 12,
            minWeight: 1079,
            targetWeight: 1106.5,
            maxWeight: 1134,
        },
        {
            uid: "wst_isa-brown-13",
            breed: "ISA Brown",
            week: 13,
            minWeight: 1169,
            targetWeight: 1199,
            maxWeight: 1229,
        },
        {
            uid: "wst_isa-brown-14",
            breed: "ISA Brown",
            week: 14,
            minWeight: 1255,
            targetWeight: 1287,
            maxWeight: 1319,
        },
        {
            uid: "wst_isa-brown-15",
            breed: "ISA Brown",
            week: 15,
            minWeight: 1335,
            targetWeight: 1369.5,
            maxWeight: 1404,
        },
        {
            uid: "wst_isa-brown-16",
            breed: "ISA Brown",
            week: 16,
            minWeight: 1409,
            targetWeight: 1445,
            maxWeight: 1481,
        },
        {
            uid: "wst_isa-brown-17",
            breed: "ISA Brown",
            week: 17,
            minWeight: 1476,
            targetWeight: 1514,
            maxWeight: 1552,
        },
        {
            uid: "wst_isa-brown-18",
            breed: "ISA Brown",
            week: 18,
            minWeight: 1537,
            targetWeight: 1576,
            maxWeight: 1615,
        },

        // ============================================================
        // NOVOgen TINTED
        // ============================================================

        {
            uid: "wst-novogen-tinted-01",
            breed: "NOVOgen Tinted",
            week: 1,
            minWeight: 63,
            targetWeight: 65.5,
            maxWeight: 68,
        },
        {
            uid: "wst-novogen-tinted-02",
            breed: "NOVOgen Tinted",
            week: 2,
            minWeight: 105,
            targetWeight: 110,
            maxWeight: 115,
        },
        {
            uid: "wst-novogen-tinted-03",
            breed: "NOVOgen Tinted",
            week: 3,
            minWeight: 185,
            targetWeight: 190,
            maxWeight: 195,
        },
        {
            uid: "wst-novogen-tinted-04",
            breed: "NOVOgen Tinted",
            week: 4,
            minWeight: 270,
            targetWeight: 277.5,
            maxWeight: 285,
        },
        {
            uid: "wst-novogen-tinted-05",
            breed: "NOVOgen Tinted",
            week: 5,
            minWeight: 365,
            targetWeight: 375,
            maxWeight: 385,
        },
        {
            uid: "wst-novogen-tinted-06",
            breed: "NOVOgen Tinted",
            week: 6,
            minWeight: 460,
            targetWeight: 472.5,
            maxWeight: 485,
        },
        {
            uid: "wst-novogen-tinted-07",
            breed: "NOVOgen Tinted",
            week: 7,
            minWeight: 550,
            targetWeight: 565,
            maxWeight: 580,
        },
        {
            uid: "wst-novogen-tinted-08",
            breed: "NOVOgen Tinted",
            week: 8,
            minWeight: 640,
            targetWeight: 655,
            maxWeight: 670,
        },
        {
            uid: "wst-novogen-tinted-09",
            breed: "NOVOgen Tinted",
            week: 9,
            minWeight: 725,
            targetWeight: 745,
            maxWeight: 765,
        },
        {
            uid: "wst-novogen-tinted-10",
            breed: "NOVOgen Tinted",
            week: 10,
            minWeight: 810,
            targetWeight: 840,
            maxWeight: 870,
        },
        {
            uid: "wst-novogen-tinted-11",
            breed: "NOVOgen Tinted",
            week: 11,
            minWeight: 900,
            targetWeight: 927.5,
            maxWeight: 955,
        },
        {
            uid: "wst-novogen-tinted-12",
            breed: "NOVOgen Tinted",
            week: 12,
            minWeight: 985,
            targetWeight: 1020,
            maxWeight: 1055,
        },
        {
            uid: "wst-novogen-tinted-13",
            breed: "NOVOgen Tinted",
            week: 13,
            minWeight: 1075,
            targetWeight: 1107.5,
            maxWeight: 1140,
        },
        {
            uid: "wst-novogen-tinted-14",
            breed: "NOVOgen Tinted",
            week: 14,
            minWeight: 1150,
            targetWeight: 1182.5,
            maxWeight: 1215,
        },
        {
            uid: "wst-novogen-tinted-15",
            breed: "NOVOgen Tinted",
            week: 15,
            minWeight: 1230,
            targetWeight: 1262.5,
            maxWeight: 1295,
        },
        {
            uid: "wst-novogen-tinted-16",
            breed: "NOVOgen Tinted",
            week: 16,
            minWeight: 1305,
            targetWeight: 1342.5,
            maxWeight: 1380,
        },
        {
            uid: "wst-novogen-tinted-17",
            breed: "NOVOgen Tinted",
            week: 17,
            minWeight: 1380,
            targetWeight: 1420,
            maxWeight: 1460,
        },
        {
            uid: "wst-novogen-tinted-18",
            breed: "NOVOgen Tinted",
            week: 18,
            minWeight: 1450,
            targetWeight: 1490,
            maxWeight: 1530,
        },

        // ============================================================
        // NOVOgen BROWN
        // ============================================================

        {
            uid: "wst-novogen-brown-01",
            breed: "NOVOgen Brown",
            week: 1,
            minWeight: 65,
            targetWeight: 67.5,
            maxWeight: 70,
        },
        {
            uid: "wst-novogen-brown-02",
            breed: "NOVOgen Brown",
            week: 2,
            minWeight: 110,
            targetWeight: 115,
            maxWeight: 120,
        },
        {
            uid: "wst-novogen-brown-03",
            breed: "NOVOgen Brown",
            week: 3,
            minWeight: 180,
            targetWeight: 185,
            maxWeight: 190,
        },
        {
            uid: "wst-novogen-brown-04",
            breed: "NOVOgen Brown",
            week: 4,
            minWeight: 270,
            targetWeight: 277.5,
            maxWeight: 285,
        },
        {
            uid: "wst-novogen-brown-05",
            breed: "NOVOgen Brown",
            week: 5,
            minWeight: 360,
            targetWeight: 372.5,
            maxWeight: 385,
        },
        {
            uid: "wst-novogen-brown-06",
            breed: "NOVOgen Brown",
            week: 6,
            minWeight: 470,
            targetWeight: 482.5,
            maxWeight: 495,
        },
        {
            uid: "wst-novogen-brown-07",
            breed: "NOVOgen Brown",
            week: 7,
            minWeight: 570,
            targetWeight: 585,
            maxWeight: 600,
        },
        {
            uid: "wst-novogen-brown-08",
            breed: "NOVOgen Brown",
            week: 8,
            minWeight: 660,
            targetWeight: 677.5,
            maxWeight: 695,
        },
        {
            uid: "wst-novogen-brown-09",
            breed: "NOVOgen Brown",
            week: 9,
            minWeight: 750,
            targetWeight: 770,
            maxWeight: 790,
        },
        {
            uid: "wst-novogen-brown-10",
            breed: "NOVOgen Brown",
            week: 10,
            minWeight: 840,
            targetWeight: 870,
            maxWeight: 900,
        },
        {
            uid: "wst-novogen-brown-11",
            breed: "NOVOgen Brown",
            week: 11,
            minWeight: 930,
            targetWeight: 960,
            maxWeight: 990,
        },
        {
            uid: "wst-novogen-brown-12",
            breed: "NOVOgen Brown",
            week: 12,
            minWeight: 1020,
            targetWeight: 1055,
            maxWeight: 1090,
        },
        {
            uid: "wst-novogen-brown-13",
            breed: "NOVOgen Brown",
            week: 13,
            minWeight: 1110,
            targetWeight: 1145,
            maxWeight: 1180,
        },
        {
            uid: "wst-novogen-brown-14",
            breed: "NOVOgen Brown",
            week: 14,
            minWeight: 1190,
            targetWeight: 1222.5,
            maxWeight: 1255,
        },
        {
            uid: "wst-novogen-brown-15",
            breed: "NOVOgen Brown",
            week: 15,
            minWeight: 1270,
            targetWeight: 1305,
            maxWeight: 1340,
        },
        {
            uid: "wst-novogen-brown-16",
            breed: "NOVOgen Brown",
            week: 16,
            minWeight: 1350,
            targetWeight: 1387.5,
            maxWeight: 1425,
        },
        {
            uid: "wst-novogen-brown-17",
            breed: "NOVOgen Brown",
            week: 17,
            minWeight: 1430,
            targetWeight: 1470,
            maxWeight: 1510,
        },
        {
            uid: "wst-novogen-brown-18",
            breed: "NOVOgen Brown",
            week: 18,
            minWeight: 1500,
            targetWeight: 1540,
            maxWeight: 1580,
        },

        // ============================================================
        // NOVOgen WHITE
        // ============================================================

        {
            uid: "wst-novogen-white-01",
            breed: "NOVOgen White",
            week: 1,
            minWeight: 70,
            targetWeight: 72.5,
            maxWeight: 75,
        },
        {
            uid: "wst-novogen-white-02",
            breed: "NOVOgen White",
            week: 2,
            minWeight: 125,
            targetWeight: 127.5,
            maxWeight: 130,
        },
        {
            uid: "wst-novogen-white-03",
            breed: "NOVOgen White",
            week: 3,
            minWeight: 190,
            targetWeight: 195,
            maxWeight: 200,
        },
        {
            uid: "wst-novogen-white-04",
            breed: "NOVOgen White",
            week: 4,
            minWeight: 270,
            targetWeight: 277.5,
            maxWeight: 285,
        },
        {
            uid: "wst-novogen-white-05",
            breed: "NOVOgen White",
            week: 5,
            minWeight: 345,
            targetWeight: 355,
            maxWeight: 365,
        },
        {
            uid: "wst-novogen-white-06",
            breed: "NOVOgen White",
            week: 6,
            minWeight: 425,
            targetWeight: 437.5,
            maxWeight: 450,
        },
        {
            uid: "wst-novogen-white-07",
            breed: "NOVOgen White",
            week: 7,
            minWeight: 500,
            targetWeight: 515,
            maxWeight: 530,
        },
        {
            uid: "wst-novogen-white-08",
            breed: "NOVOgen White",
            week: 8,
            minWeight: 575,
            targetWeight: 590,
            maxWeight: 605,
        },
        {
            uid: "wst-novogen-white-09",
            breed: "NOVOgen White",
            week: 9,
            minWeight: 650,
            targetWeight: 667.5,
            maxWeight: 685,
        },
        {
            uid: "wst-novogen-white-10",
            breed: "NOVOgen White",
            week: 10,
            minWeight: 720,
            targetWeight: 740,
            maxWeight: 760,
        },
        {
            uid: "wst-novogen-white-11",
            breed: "NOVOgen White",
            week: 11,
            minWeight: 790,
            targetWeight: 812.5,
            maxWeight: 835,
        },
        {
            uid: "wst-novogen-white-12",
            breed: "NOVOgen White",
            week: 12,
            minWeight: 855,
            targetWeight: 880,
            maxWeight: 905,
        },
        {
            uid: "wst-novogen-white-13",
            breed: "NOVOgen White",
            week: 13,
            minWeight: 920,
            targetWeight: 945,
            maxWeight: 970,
        },
        {
            uid: "wst-novogen-white-14",
            breed: "NOVOgen White",
            week: 14,
            minWeight: 980,
            targetWeight: 1007.5,
            maxWeight: 1035,
        },
        {
            uid: "wst-novogen-white-15",
            breed: "NOVOgen White",
            week: 15,
            minWeight: 1045,
            targetWeight: 1075,
            maxWeight: 1105,
        },
        {
            uid: "wst-novogen-white-16",
            breed: "NOVOgen White",
            week: 16,
            minWeight: 1110,
            targetWeight: 1140,
            maxWeight: 1170,
        },
        {
            uid: "wst-novogen-white-17",
            breed: "NOVOgen White",
            week: 17,
            minWeight: 1170,
            targetWeight: 1202.5,
            maxWeight: 1235,
        },
        {
            uid: "wst-novogen-white-18",
            breed: "NOVOgen White",
            week: 18,
            minWeight: 1230,
            targetWeight: 1265,
            maxWeight: 1300,
        },

        // ============================================================
        // HY-LINE BROWN MAX
        // ============================================================

        {
            uid: "wst-hyline-brown-max-01",
            breed: "Hy-Line Brown Max",
            week: 1,
            minWeight: 70,
            targetWeight: 73,
            maxWeight: 76,
        },
        {
            uid: "wst-hyline-brown-max-02",
            breed: "Hy-Line Brown Max",
            week: 2,
            minWeight: 127,
            targetWeight: 132,
            maxWeight: 138,
        },
        {
            uid: "wst-hyline-brown-max-03",
            breed: "Hy-Line Brown Max",
            week: 3,
            minWeight: 192,
            targetWeight: 200,
            maxWeight: 208,
        },
        {
            uid: "wst-hyline-brown-max-04",
            breed: "Hy-Line Brown Max",
            week: 4,
            minWeight: 267,
            targetWeight: 278,
            maxWeight: 289,
        },
        {
            uid: "wst-hyline-brown-max-05",
            breed: "Hy-Line Brown Max",
            week: 5,
            minWeight: 353,
            targetWeight: 368,
            maxWeight: 383,
        },
        {
            uid: "wst-hyline-brown-max-06",
            breed: "Hy-Line Brown Max",
            week: 6,
            minWeight: 447,
            targetWeight: 466,
            maxWeight: 485,
        },
        {
            uid: "wst-hyline-brown-max-07",
            breed: "Hy-Line Brown Max",
            week: 7,
            minWeight: 546,
            targetWeight: 569,
            maxWeight: 591,
        },
        {
            uid: "wst-hyline-brown-max-08",
            breed: "Hy-Line Brown Max",
            week: 8,
            minWeight: 646,
            targetWeight: 673,
            maxWeight: 700,
        },
        {
            uid: "wst-hyline-brown-max-09",
            breed: "Hy-Line Brown Max",
            week: 9,
            minWeight: 747,
            targetWeight: 778,
            maxWeight: 809,
        },
        {
            uid: "wst-hyline-brown-max-10",
            breed: "Hy-Line Brown Max",
            week: 10,
            minWeight: 845,
            targetWeight: 880,
            maxWeight: 916,
        },
        {
            uid: "wst-hyline-brown-max-11",
            breed: "Hy-Line Brown Max",
            week: 11,
            minWeight: 940,
            targetWeight: 979,
            maxWeight: 1018,
        },
        {
            uid: "wst-hyline-brown-max-12",
            breed: "Hy-Line Brown Max",
            week: 12,
            minWeight: 1029,
            targetWeight: 1072,
            maxWeight: 1114,
        },
        {
            uid: "wst-hyline-brown-max-13",
            breed: "Hy-Line Brown Max",
            week: 13,
            minWeight: 1111,
            targetWeight: 1157,
            maxWeight: 1203,
        },
        {
            uid: "wst-hyline-brown-max-14",
            breed: "Hy-Line Brown Max",
            week: 14,
            minWeight: 1186,
            targetWeight: 1236,
            maxWeight: 1285,
        },
        {
            uid: "wst-hyline-brown-max-15",
            breed: "Hy-Line Brown Max",
            week: 15,
            minWeight: 1257,
            targetWeight: 1310,
            maxWeight: 1362,
        },
        {
            uid: "wst-hyline-brown-max-16",
            breed: "Hy-Line Brown Max",
            week: 16,
            minWeight: 1326,
            targetWeight: 1381,
            maxWeight: 1437,
        },
        {
            uid: "wst-hyline-brown-max-17",
            breed: "Hy-Line Brown Max",
            week: 17,
            minWeight: 1393,
            targetWeight: 1451,
            maxWeight: 1509,
        },
        {
            uid: "wst-hyline-brown-max-18",
            breed: "Hy-Line Brown Max",
            week: 18,
            minWeight: 1460,
            targetWeight: 1515,
            maxWeight: 1570,
        },

        // ============================================================
        // DEKALB WHITE
        // ============================================================

        {
            uid: "wst-dekalb-white-01",
            breed: "Dekalb White",
            week: 1,
            minWeight: 65,
            targetWeight: 67,
            maxWeight: 69,
        },
        {
            uid: "wst-dekalb-white-02",
            breed: "Dekalb White",
            week: 2,
            minWeight: 125,
            targetWeight: 128.5,
            maxWeight: 132,
        },
        {
            uid: "wst-dekalb-white-03",
            breed: "Dekalb White",
            week: 3,
            minWeight: 194,
            targetWeight: 199,
            maxWeight: 204,
        },
        {
            uid: "wst-dekalb-white-04",
            breed: "Dekalb White",
            week: 4,
            minWeight: 266,
            targetWeight: 273,
            maxWeight: 280,
        },
        {
            uid: "wst-dekalb-white-05",
            breed: "Dekalb White",
            week: 5,
            minWeight: 341,
            targetWeight: 350,
            maxWeight: 359,
        },
        {
            uid: "wst-dekalb-white-06",
            breed: "Dekalb White",
            week: 6,
            minWeight: 419,
            targetWeight: 429.5,
            maxWeight: 440,
        },
        {
            uid: "wst-dekalb-white-07",
            breed: "Dekalb White",
            week: 7,
            minWeight: 498,
            targetWeight: 511,
            maxWeight: 524,
        },
        {
            uid: "wst-dekalb-white-08",
            breed: "Dekalb White",
            week: 8,
            minWeight: 579,
            targetWeight: 594,
            maxWeight: 609,
        },
        {
            uid: "wst-dekalb-white-09",
            breed: "Dekalb White",
            week: 9,
            minWeight: 660,
            targetWeight: 677,
            maxWeight: 694,
        },
        {
            uid: "wst-dekalb-white-10",
            breed: "Dekalb White",
            week: 10,
            minWeight: 735,
            targetWeight: 752.5,
            maxWeight: 770,
        },
        {
            uid: "wst-dekalb-white-11",
            breed: "Dekalb White",
            week: 11,
            minWeight: 820,
            targetWeight: 837.5,
            maxWeight: 855,
        },
        {
            uid: "wst-dekalb-white-12",
            breed: "Dekalb White",
            week: 12,
            minWeight: 905,
            targetWeight: 922.5,
            maxWeight: 940,
        },
        {
            uid: "wst-dekalb-white-13",
            breed: "Dekalb White",
            week: 13,
            minWeight: 980,
            targetWeight: 997.5,
            maxWeight: 1015,
        },
        {
            uid: "wst-dekalb-white-14",
            breed: "Dekalb White",
            week: 14,
            minWeight: 1060,
            targetWeight: 1077.5,
            maxWeight: 1095,
        },
        {
            uid: "wst-dekalb-white-15",
            breed: "Dekalb White",
            week: 15,
            minWeight: 1130,
            targetWeight: 1147.5,
            maxWeight: 1165,
        },
        {
            uid: "wst-dekalb-white-16",
            breed: "Dekalb White",
            week: 16,
            minWeight: 1190,
            targetWeight: 1207.5,
            maxWeight: 1225,
        },
        {
            uid: "wst-dekalb-white-17",
            breed: "Dekalb White",
            week: 17,
            minWeight: 1250,
            targetWeight: 1267.5,
            maxWeight: 1285,
        },
        {
            uid: "wst-dekalb-white-18",
            breed: "Dekalb White",
            week: 18,
            minWeight: 1243,
            targetWeight: 1275,
            maxWeight: 1307,
        },

        // ============================================================
        // LOHMANN BROWN-CLASSIC
        // ============================================================

        {
            uid: "wst-lohmann-brown-classic-01",
            breed: "Lohmann Brown-Classic",
            week: 1,
            minWeight: 73,
            targetWeight: 75,
            maxWeight: 77,
        },
        {
            uid: "wst-lohmann-brown-classic-02",
            breed: "Lohmann Brown-Classic",
            week: 2,
            minWeight: 126,
            targetWeight: 130,
            maxWeight: 134,
        },
        {
            uid: "wst-lohmann-brown-classic-03",
            breed: "Lohmann Brown-Classic",
            week: 3,
            minWeight: 189,
            targetWeight: 195,
            maxWeight: 201,
        },
        {
            uid: "wst-lohmann-brown-classic-04",
            breed: "Lohmann Brown-Classic",
            week: 4,
            minWeight: 265,
            targetWeight: 273,
            maxWeight: 281,
        },
        {
            uid: "wst-lohmann-brown-classic-05",
            breed: "Lohmann Brown-Classic",
            week: 5,
            minWeight: 355,
            targetWeight: 366,
            maxWeight: 377,
        },
        {
            uid: "wst-lohmann-brown-classic-06",
            breed: "Lohmann Brown-Classic",
            week: 6,
            minWeight: 455,
            targetWeight: 469,
            maxWeight: 483,
        },
        {
            uid: "wst-lohmann-brown-classic-07",
            breed: "Lohmann Brown-Classic",
            week: 7,
            minWeight: 556,
            targetWeight: 573,
            maxWeight: 590,
        },
        {
            uid: "wst-lohmann-brown-classic-08",
            breed: "Lohmann Brown-Classic",
            week: 8,
            minWeight: 657,
            targetWeight: 677,
            maxWeight: 697,
        },
        {
            uid: "wst-lohmann-brown-classic-09",
            breed: "Lohmann Brown-Classic",
            week: 9,
            minWeight: 754,
            targetWeight: 777,
            maxWeight: 800,
        },
        {
            uid: "wst-lohmann-brown-classic-10",
            breed: "Lohmann Brown-Classic",
            week: 10,
            minWeight: 847,
            targetWeight: 873,
            maxWeight: 899,
        },
        {
            uid: "wst-lohmann-brown-classic-11",
            breed: "Lohmann Brown-Classic",
            week: 11,
            minWeight: 934,
            targetWeight: 963,
            maxWeight: 992,
        },
        {
            uid: "wst-lohmann-brown-classic-12",
            breed: "Lohmann Brown-Classic",
            week: 12,
            minWeight: 1016,
            targetWeight: 1047,
            maxWeight: 1078,
        },
        {
            uid: "wst-lohmann-brown-classic-13",
            breed: "Lohmann Brown-Classic",
            week: 13,
            minWeight: 1094,
            targetWeight: 1128,
            maxWeight: 1162,
        },
        {
            uid: "wst-lohmann-brown-classic-14",
            breed: "Lohmann Brown-Classic",
            week: 14,
            minWeight: 1169,
            targetWeight: 1205,
            maxWeight: 1241,
        },
        {
            uid: "wst-lohmann-brown-classic-15",
            breed: "Lohmann Brown-Classic",
            week: 15,
            minWeight: 1241,
            targetWeight: 1279,
            maxWeight: 1317,
        },
        {
            uid: "wst-lohmann-brown-classic-16",
            breed: "Lohmann Brown-Classic",
            week: 16,
            minWeight: 1310,
            targetWeight: 1351,
            maxWeight: 1392,
        },
        {
            uid: "wst-lohmann-brown-classic-17",
            breed: "Lohmann Brown-Classic",
            week: 17,
            minWeight: 1378,
            targetWeight: 1421,
            maxWeight: 1464,
        },
        {
            uid: "wst-lohmann-brown-classic-18",
            breed: "Lohmann Brown-Classic",
            week: 18,
            minWeight: 1448,
            targetWeight: 1493,
            maxWeight: 1538,
        },
    ]);

    await weightStandardRepository.upsert(weightStandards, ["uid"]);
}
