export enum PlatformCategory {
    GYM = "GYM",
    ONBOARDLY = "ONBOARDLY",
    FARMORA = "FARMORA",
    POULTRY_FARMING = "POULTRY_FARMING",
    AGRICULTURE = "AGRICULTURE",
    CATTLE_FARMING = "CATTLE_FARMING",
    PIG_FARMING = "PIG_FARMING",
}
